### ISSUE TITLE
re: time with DoubleFloats

### ISSUE THREAD

**Issue by JeffreySarnoff** [chrisvwx/LLLplus.jl#20]
I think the unexpected extra time was the result of an inefficient round(x) function.
I have improved things in DoubleFloats#master, would you mind rerunning your benchmarks and let me know if the difference is meaningful?

**Comment by chrisvwx** [comment]
Looks to me that both with the currently release of DoubleFloats and #master that DoubleFloats are now slower than previous and now have speed more like BigInts and BigFloats. See the figure and compare with the second figure on the [LLLplus.jl](https://github.com/christianpeel/LLLplus.jl) page.     One difference with this figure and that in the README is that this is done with the minimum time; I tried with the median and got similar results.
![perfVsDataType](https://user-images.githubusercontent.com/6899870/57397461-97064080-7181-11e9-889f-f8a69b9edc3a.png)

**Comment by JeffreySarnoff** [comment]
That is quite unexpected -- I do not introduce changes to slow things down, and, really, since your first measure the biggest change was to simplify the round(), and associated ciel, floor, trunc functions.
Are many of your calls to round done with floating point values that are integers already?  I removed the initial check for `(isinteger(x) || !isfinite(x)) && return round(HI(x))` or something like that, thinking that would speed it for you.  (I think both versions you tried had this change -- not sure)

**Comment by JeffreySarnoff** [comment]
can you give me some simple code that use this package in a way that roughly approximates the proportional use of math/linearalgebra functions that you have benchmarked yet runs in much more quickly (e.g. a much smaller set of input) so I may test different implementations of a few lower level aspects of DoubleFloats?  Something easy for me to use and reuse without looking at your work?

**Comment by chrisvwx** [comment]
To help me catch up with you, what caused you to notice the "unexpected extra time" that you mention above? Was it the [discussion](https://discourse.julialang.org/t/ann-quadmath-jl/23015/4) on discourse  about Quadmath.jl?  

As you requested here is a (relatively) simple code excerpt that you could use to compare the time of Float128, Double64, and BigFloats.  Of course you should run this twice to remove the pre-compilation time.  You could also try replacing the `lll` commands above with `qr`.
```
using LLLplus
using DoubleFloats
using Quadmath
N = 50;
F64 = randn(N,N);
F128 = Float128.(F64);
D64 = Double64.(F64);
Big = BigFloat.(F64);
@elapsed lll(F128)
@elapsed lll(D64)
@elapsed lll(Big)
```

**Comment by JeffreySarnoff** [comment]
That discussion provided focus.  The results of your benchmarkings highlighted the fact that, unlike other computational comparisons, your processing had shown there is some function or few functions within DoubleFloats that would benefit from hand tuning.  There is no a priori reason to think that running LLLplus using Double64 would not be noticeably faster using Float128 -- because most other tests have shown that (e.g. using either the DifferentialEquations or Optimization examples).

**Comment by chrisvwx** [comment]
To be clear, you expect processing with Float128 to be faster than Double64; is that right?     If not, did you try replacing the `lll` above with `qr` (from the LinearAlgebra package)?

**Comment by JeffreySarnoff** [comment]
NO.  I expect Double64 to be faster than Float128. 
I see that Double64 is allocating much more than perhaps it should -- although its difficult to compare because most of the allocations for Float128 and for BigFloat happen inside a C library.

**Comment by JeffreySarnoff** [comment]
At the moment Double64s are faster than Float128s with arithmetic operations and elementary functions of small arguments  (eg |x| <= 1 or 2).  And that is where I have been focused as (based on requests) current users of DoubleFloats need that most.

I have done no development specific to linear algebra e.g. `det`, `mul!`, `lu`; and so, unsurprisingly, Float128s are considerably faster than Double64s.  [I had expected better, and need to provide some software performance assist (easiest would be to use Float128s for large matrix operations ..., I have not experimented with interconversion).

**Comment by chrisvwx** [comment]
Ok, so it looks like any slowness of DoubleFloats is not specific to LLLplus; is that right?

**Comment by JeffreySarnoff** [comment]
it is not at all right
however, it is correct, 
[thanks for the give and take]

**Comment by JeffreySarnoff** [comment]
Fixed in v0.8.0 (current master, pending merge)

use BenchmarkTools (@elapsed captures more than the time to execute)

```julia
using LLLplus
using DoubleFloats
using Quadmath
using BenchmarkTools
N = 100;
F64 = randn(N,N);
F128 = Float128.(F64);
D64 = Double64.(F64);
Big = BigFloat.(F64);
@belapsed lll($F128) # 0.096
@belapsed lll($D64)  # 0.064
@belapsed lll($Big)  # 0.454
```

**Comment by chrisvwx** [comment]
Nice!  I tested it and the results look much better!

**Comment by JeffreySarnoff** [comment]
would you mind updating the comparisons on Discorse?

**Comment by chrisvwx** [comment]
I guess you mean [discourse](https://discourse.julialang.org/t/ann-quadmath-jl/23015/3); is that right?

**Comment by JeffreySarnoff** [comment]
yes
