### ISSUE TITLE
Bug in hard_sphere() ?

### ISSUE THREAD

**Issue by arbenede** [chrisvwx/LLLplus.jl#5]
I am not sure if this is a bug or I am not understanding how to call  hard_sphere() ...
If I run 
x = hard_sphere([1 2]', [1 2; 3 4],2)
I get
x = [0; 1]
this solution gives the lattice point 
 [1 2; 3 4] * [0; 1] = [2; 4]
however there are 4 lattice points ([1 1], [0 2], [1 1], [1 1], [1 3],  [2 2]) that are closer to [1 2] than [2 4].
Also, if I set the Nc input parameter to values >2 I get lattice points that move farther away from the closest point, so I am not sure what is going on...

**Comment by chrisvwx** [comment]
Yes, you're right, there was a bug.   Specifically, [line 28](https://github.com/christianpeel/LLLplus.jl/blob/master/src/hard_sphere.jl#L28) of hard_sphere.jl should be uncommented, and the following line removed.  I'll fix this soon.

**Comment by chrisvwx** [comment]
It wasn't especially soon, but this is fixed. I haven't yet updated the METADATA.jl repo so (assuming you're on 0.7 or 1.0), the easiest way to see the change is with the following command:
`Pkg.add(PackageSpec(url="https://github.com/christianpeel/LLLplus.jl", rev="master"))`
