### ISSUE TITLE
Getting rid of allocations in the lll function

### ISSUE THREAD

**Issue by saolof** [chrisvwx/LLLplus.jl#59]
After writing a quick LLL implementation [(gist here)](https://gist.github.com/saolof/d2fcd64a9d747bc9a30774d7b0902db1) using Givens rotations to get better aquainted with lattice problems while learning lattice-based cryptography, I started to benchmark the available LLL implementations.

The LLL function in this package is fairly well optimized but it does seem to make a bunch of allocations that can probably be done away with, and there may be a ~2x speedup available from getting rid of them. Tracking them down may be somewhat nontrivial but it should be a low-hanging fruit for further optimization.

**Comment by chrisvwx** [comment]
Thanks for the comment!

The gist you point to seems to be for Givens rotations; did you mean to point to another gist which has a Householder implementation?

This library sees so little use that optimizing it is not high on my priorities.  I confess that it's not clear to me why minimizing the number of allocations would lead to a speedup; could you explain this?

**Comment by saolof** [comment]
Ah, I ended up switching to just using Givens rotations in that gist since that turned out to be simpler. Reducing memory allocations is just a generic suggestion that often helps Julia since allocations are usually more expensive in Julia than in runtimes that have a compacting GC so that they can use bump allocation. 

But I understand not prioritizing this too much because I can't think of a lot of applications where LLL performance is the actual bottleneck as long as it's fast enough, since the bottleneck in lattice problems is usually the steps you do after having reduced the basis.
