### ISSUE TITLE
`cvp` does not work correctly

### ISSUE THREAD

**Issue by GiggleLiu** [chrisvwx/LLLplus.jl#61]
```julia
cvp([-2, 0.0], Matrix([1 1.0; 4 0]'))
```

It got stuck in this expression. It only has dimension 2.

**Comment by chrisvwx** [comment]
`Matrix([1 1.0; 4 0]')` is not upper triangular as required for the second argument of `cvp`.    It's not clear to me what problem you want to solve.   Did you mean to use code shown below (which is adapted from the help text of `cvp`)?

```
H = Matrix([1 1.0; 4 0]');
Q,R = qr(H);
uhat = cvp(Q'*[-2,0],R)
```

**Comment by GiggleLiu** [comment]
Thanks, that makes sense. It is safer to dispatch it on `UpperTriangular` type in my opinion, then people has no chance to input the incorrect arguments.
